<? 
include "header.php";
head(3, "Create Account");

$link = mysql_connect("localhost", "root", "") or die("Could not connect: " . mysql_error());
mysql_select_db("rpg", $link);

if (@$_GET["validate"]) {
//if (@$_GET["validate"] && @$_GET["username"]) {
$username = urlencode($_GET["username"]);

//if ($_GET["validate"] == md5("X!> $username <!X")) {
if ($username) {
if (mysql_query("UPDATE `users` SET `validated` = 'y' WHERE `username` = '$username'", $link)) {

if (!mysql_fetch_row(mysql_query("SELECT `username` , `levelname` FROM `map` WHERE 1 AND `username` = '".$username."' AND `levelname` = 'level'", $link))) {
$avitar = mysql_fetch_row(mysql_query("SELECT `avitar` FROM `users` WHERE 1 AND `username` = '".$username."' ", $link)); $avitar = $avitar[0];
echo "Database entry for default rpg ('level') made<br>";
mysql_query("INSERT INTO `map` ( `username` , `levelname` , `fight` , `xpos` , `ypos` , `kills` , `hp` , `def` , `acc` , `atk` , `spd` , `avitar`) VALUES ( '".$username."', 'level', 'n', '0', '0', '', '5', '1', '1', '1', '1', '".$avitar."' ); ", $link);
}
echo "your account has been validated, and you can now <a href=login.php>login</a>";
foot(1);
exit;
} else {
echo "ack... it is possible that your account was deleted [cause you took too long, you lazy bum :P] or there was a database error. <br><a href=create.php>Create a new acocunt<a>";
foot(1);
exit;
}
} else {
echo "Bad validation key - error";
foot(1);
exit;
}
}

$eemail = true;
$euser = true;

if (@$_POST["username"] && @$_POST["password"] && @$_POST["vpassword"] && @$_POST["avitar"] && @$_POST["email"] && ($_POST["password"] == $_POST["vpassword"])) {

$username = urlencode($_POST["username"]);
$password = urlencode($_POST["password"]);
$avitar = urlencode($_POST["avitar"]);
$email = $_POST["email");


if (!ereg("[[:alnum:]]+@[[:alnum:]]+\.[[:alnum:]]+", $email)) {
$eemail = false;
}

if (mysql_fetch_row(mysql_query("SELECT `username` FROM `users` WHERE `username` = '".$username."'", $link))) {
$euser = false;
} else {
if ($eemail == true) {

mysql_query("INSERT INTO `users` ( `username` , `password` , `avitar` , `email` , `created`, `validated` ) VALUES ( '".$username."', '".$password."', '".$avitar."', '".$email."', '".time()."', 'y' );", $link);

$validate = md5("X!> $username <!X");
       $msg = "Your tnt account details are as follows:\r\n";
$msg = $msg." \r\n";
$msg = $msg."Username: $username\r\n";
$msg = $msg."Password: {$_POST["password"]}\r\n";
$msg = $msg." \r\n";
$msg = $msg."If you wish to keep your account, you must validate it within 2 weeks.\r\n";
$msg = $msg." \r\n";
$msg = $msg."This can be done by visiting http://{$_SERVER["HTTP_HOST"]}{$_SERVER["PHP_SELF"]}/create.php?validate=$validate&username=$username\r\n";
$msg = $msg." \r\n";
$msg = $msg." \r\n";
$msg = $msg."Message auto-generated by {$_SERVER["HTTP_HOST"]} - If you did not expect this email, please delete it.\r\n";

mysql_query("UPDATE `users` SET `validated` = 'y' WHERE `username` = '$username'", $link);
if (!mysql_fetch_row(mysql_query("SELECT `username` , `levelname` FROM `map` WHERE 1 AND `username` = '".$username."' AND `levelname` = 'level'", $link))) {
$avitar = ".gif"; $avitar = $avitar[0];
echo "Database entry for default rpg ('level') made<br>";
mysql_query("INSERT INTO `map` ( `username` , `levelname` , `fight` , `xpos` , `ypos` , `kills` , `hp` , `def` , `acc` , `atk` , `spd` , `avitar`) VALUES ( '".$username."', 'level', 'n', '0', '0', '', '5', '1', '1', '1', '1', '".$avitar."' ); ", $link);
}

//mail($email, "Account activation", $msg, "From: NoReply@{$_SERVER["HTTP_HOST"]} <idiotproof@paradise.net.nz>\r\n");
//echo "Please check your email for a validation key.<br>\nYour account will be deleted in 2 weeks if not validated.<br>\n<br>Then, you can <a href=login.php>login</a>";

$forum = mysql_connect("localhost", "root", "") or die("Could not connect: " . mysql_error());
mysql_select_db("forum", $forum);
mysql_query("INSERT INTO `rpg_users` ( `id` , `username` , `password` , `email` , `title` , `realname` , `url` , `icq` , `msn` , `aim` , `yahoo` , `location` , `use_avatar` , `signature` , `disp_topics` , `disp_posts` , `email_setting` , `save_pass` , `notify_with_post` , `smilies` , `show_img` , `show_avatars` , `show_sig` , `link_to_new_win` , `timezone` , `style` , `num_posts` , `status` , `last_post` , `registered` , `last_visit` , `last_action` , `admin_note` , `activate_string` , `activate_key` )VALUES ( '', '".$username."', '".md5($password)."', '".$email."', NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , '0', NULL , NULL , NULL , '0', '1', '0', '1', '1', '1', '1', '1', '0', 'Mercury', '0', '-1', NULL , '".date("U")."', '0', '0', NULL , NULL , NULL);", $forum);




foot(1);
exit;
}
}

}

if (@$_POST['send'] && @$euser == true && @$eemail == true) {
echo "<b>You must complete all the required parts of the form</b>";
}

if (@$euser == false) { $euser = "<b>Username \"{$username}\" is taken</b>"; } else { @$euser = ""; }
if (@$eemail == false) { $eemail = "<b>Please enter a VALID email address</b>"; } else { @$eemail = ""; }

?>
<script>
function pwval() {
if (document.create.password.value == document.create.vpassword.value) {
return true;
} else {
alert ("The passwords MUST match!");
return false;
}
}
function newword() {
// magical random pronouncable word maker
// ITS LIKE A DICTIONARY THAT CANT SPELL FOR SHIRT!!!
// by idiotproof [copyright 2003]
// wanna use it on some (crappy :P) site of yours? ask!
var w = "abcdefghijklmnopqrstuvwxy"; var v = "aeiou";
var string = ""; var slen = (Math.floor(Math.random()*3)) + 2;
for (let = 0; let < slen; let++) {
string = string + w.charAt(Math.floor(Math.random()*w.length));
string = string + v.charAt(Math.floor(Math.random()*v.length));
}
string = string + w.charAt(Math.floor(Math.random()*w.length));
return string; }
</script>
<?
echo "<form name=create action=create.php method=post onSubmit='return pwval();'> \n";
echo "username: <input type=text value='".@$_POST['username']."' name=username><DISABLED Xinput type=button value=random onClick='document.create.username.value = newword();'> ".@$euser."<br>\n";
echo "password: <input type=password name=password><br>\n";
echo "verify password: <input type=password name=vpassword><br>\n";
echo "avitar: <select name=avitar onChange=\"document.create.apre.src='images/objects/'+this.value;\"><option value=models/bug_smile.gif>smile<option value=models/bug_blush.gif>blush<option value=models/bug_thinking.gif>=/<option value=models/bug_tongue.gif>:P<option value=models/bug_laugh.gif>=D</select> - ";
echo "<img name=apre src=images/objects/models/bug_smile.gif><br>\n";
echo "email: <input type=text value='".@$_POST['email']."' name=email> ".@$eemail." [email is needed to complete registration]<br>\n";
?>

<textarea rows=5 cols=50>
Terms & Conditions
[complete and utter draft]

well... if there is any loss of/damage caused to property during your time at this site, no liability will be accepted.
you agree to allow your data/accounts to be edited/deleted without prior permission, and you surrender all personal copyrights on any data/content/etc posted/used on this site

these terms and conditions may change at any time. you are responsible for checking for these updates as long as you operate  our services
</textarea><br>
I agree to the terms and conditions <input name=terms type=checkbox onClick="if (this.checked == false) { document.create.send.disabled = true; } else { document.create.send.disabled = false; } "><br>
<script>document.create.terms.checked=false;</script>
<input type=submit name=send value=register disabled=true></form>

<? foot(1); ?>
